package.json
src/export/word/schema.ts
yarn.lock

Requires https://github.com/curvenote/prosemirror-docx/pull/8

serialize figure captions with working references

---

package.json
src/actions/utils.ts
src/export/tex/index.ts
src/export/utils/imagemagick.ts
src/export/utils/localizationOptions.ts
src/export/utils/walkArticle.ts
yarn.lock

- 🧙🏼 code, outputs and gifs handled - default renders test article
TODO:

Get tex & pdf output handling to status quo

---

src/export/utils/walkArticle.ts

Previously we were only rendering `output.contents` (which is truncated for large HTML strings) rather than fetching the full HTML payload from storage. fixes #31

⏬  fetch full html content when needed

---

package-lock.json
package.json
scripts/updateAuthors.ts
src/web/cache.ts
src/web/files.ts
src/web/index.ts
src/web/transforms/outputs.ts

using new tighter data structures

next pass on juptyer outputs

---

package.json
src/web/transforms/keys.ts
src/web/transforms/root.ts
src/web/transforms/types.ts
src/web/utils.ts
tsconfig.json

Changes helps setting up monorepo.

Update mystjs. Add more definitive return type

---

src/config/index.ts
src/config/types.ts
src/web/cache.ts
src/web/frontmatter.ts
src/web/licenses.json
src/web/licenses.ts
src/web/transforms/index.ts
src/web/transforms/math.ts
src/web/transforms/types.ts
src/web/types.ts
src/web/webConfig.ts

📖  Frontmatter can be loaded from folder _config.yml or curvenote.yml

---

src/web/files.ts
src/web/transforms/images.ts

🌠 Support inline base64 encoded images in markdown

---

src/session/session.ts
src/utils.ts

this will display a useful error message on this specific `400` error see #80 for a screenshot

🛑  handle API rejection when client is out of date

---

src/config/types.ts
src/export/tex/single.ts
src/utils.ts
src/web/frontmatter.ts
src/web/licenses.ts

👩‍⚖️ Code and content licenses

---

npm-shrinkwrap.json
package.json
src/web/transforms/citations.ts
src/web/transforms/dois.ts
src/web/transforms/index.ts

🪄  Transform links with DOIs into citations

---

.github/workflows/test.yml
npm-shrinkwrap.json
package.json
src/cli/services/utils/utils.ts
src/sync/pull.ts

🚒 Add node engines that are supported

---

src/store/local/actions.ts
src/transforms/admonitions.ts
src/transforms/index.ts

☎️  Admonition titles

---

src/toc/index.ts
src/toc/toc.spec.ts

Resolves: https://github.com/curvenote/curvenotejs/issues/119

🤸‍♀️ Have more flexibility auto-selecting project index file

---

src/config/config.spec.ts
src/config/index.ts
src/config/validators.ts
src/frontmatter/api.ts
src/frontmatter/frontmatter.spec.ts
src/frontmatter/validators.ts
src/licenses/licenses.spec.ts
src/licenses/validators.ts
src/logging/index.ts
src/sync/pull.ts
src/toc/index.ts
src/utils/validators.spec.ts
src/utils/validators.ts

Pull (and clone and init) update local project frontmatter 

---

src/licenses/licenses.spec.ts
src/licenses/validators.ts

eliminates this duplication here:

👩‍💼 Modify license coersion - string -> content only, matching content/code dedup

---

src/cli/utils.ts
src/config/index.ts
src/export/jupyter-book/exportAll.ts
src/export/jupyter-book/index.ts
src/export/markdown/index.ts
src/export/notebook/index.ts
src/frontmatter/api.ts
src/frontmatter/frontmatter.spec.ts
src/frontmatter/index.ts
src/frontmatter/types.ts
src/frontmatter/validators.ts
src/store/local/actions.ts
src/store/local/index.ts
src/store/local/reducers.ts
src/store/local/selectors.ts
src/sync/pull.ts
src/utils/validators.spec.ts
src/utils/validators.ts

Improve page frontmatter

---

src/sync/clone.ts

🐑 Respect clone path; no '.' default

---

src/cli/web.ts
src/web/index.ts

🤖  add `-ci` option for `deploy`

---

src/store/local/actions.spec.ts
src/store/local/actions.ts

Addresses #166 - Invalid notebooks (or md or bib files) log an error but web build continues.

⚾️ Catch errors and continue when loading files for web build

---

src/store/local/actions.ts
src/store/local/reducers.ts
src/store/local/selectors.ts
src/transforms/images.ts
src/transforms/links.spec.ts
src/transforms/links.ts
src/transforms/types.ts
src/utils/utils.ts
src/web/files.ts

Addresses: https://github.com/curvenote/curvenotejs/issues/176

🔗 Transform relative links to resolve correctly

---

src/toc/index.ts
src/toc/toc.spec.ts

🗂 Files before folders in implicit toc

---

src/transforms/links.ts

fixes #196 
the links themselves then appear to work in the same way as before

🔖 fix spurious copy image errors

---

npm-shrinkwrap.json
package.json
src/export/utils/walkArticle.ts
src/transforms/images.ts

Fixes:
- #180 
- #195
Requires:
- https://github.com/curvenote/schema/issues/70
- https://github.com/curvenote/curvespace/pull/93

🌠 Image width and alignment

---

src/transforms/dois.ts

Allows you to create citations with a DOI directly rather than a bibtex.

🔗 Add DOIs for citations and links

---

src/web/deploy.ts

🚨 Throw error when site promotion fails
